// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/delivery/zsx//delivery_dashboard.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Order = @import("../../orders/models/order.zig").Order;

pub const DeliveryDashboard = struct {
    orders: []Order,
    sse_init: []const u8 = "",

    pub fn render(self: DeliveryDashboard, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 10 "src/features/delivery/zsx//delivery_dashboard.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"max-w-6xl mx-auto p-4 lg:p-6\" data-init=\"");
    try appendValue(out, allocator, self.sse_init);
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<header class=\"flex items-center justify-between mb-6\">");
    try out.appendSlice(allocator, "<div class=\"flex items-center gap-3\">");
    try out.appendSlice(allocator, "<div class=\"w-10 h-10 rounded-xl bg-blue-100 text-blue-600 flex items-center justify-center text-xl\">");
    try out.appendSlice(allocator, "🛵");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<h1 class=\"text-xl font-bold text-slate-800\">");
    try out.appendSlice(allocator, "Delivery");
    try out.appendSlice(allocator, "</h1>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-500\">");
    try out.appendSlice(allocator, "Pick up Ready orders and mark Delivered when handed off.");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<span class=\"text-xs text-slate-500 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-emerald-50 text-emerald-700\">");
    try out.appendSlice(allocator, "<span class=\"w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse\">");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "Live");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</header>");
    if (self.orders.len == 0) {
    try out.appendSlice(allocator, "<div class=\"bg-white rounded-2xl border border-slate-200 p-12 text-center\">");
    try out.appendSlice(allocator, "<div class=\"text-5xl mb-3\">");
    try out.appendSlice(allocator, "🪧");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<p class=\"text-sm font-medium text-slate-700\">");
    try out.appendSlice(allocator, "Nothing to deliver right now");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mt-1\">");
    try out.appendSlice(allocator, "Ready orders will appear here as the kitchen completes them.");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    } else {
    try out.appendSlice(allocator, "<div class=\"grid grid-cols-1 lg:grid-cols-2 gap-4\">");
    try out.appendSlice(allocator, "<section>");
    try out.appendSlice(allocator, "<div class=\"flex items-center justify-between mb-2 px-1\">");
    try out.appendSlice(allocator, "<h2 class=\"text-xs font-semibold text-slate-500 uppercase tracking-wider\">");
    try out.appendSlice(allocator, "Ready");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<span class=\"text-xs text-slate-400\">");
    try out.appendSlice(allocator, "pick up from kitchen");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"space-y-3\">");
    for (self.orders) |o| {
    if (o.isStatusCurrent("Ready")) {
    try out.appendSlice(allocator, "<article class=\"bg-white rounded-xl border border-emerald-200 shadow-sm overflow-hidden\">");
    try out.appendSlice(allocator, "<header class=\"px-4 py-3 bg-emerald-50 border-b border-emerald-100 flex items-center justify-between\">");
    try out.appendSlice(allocator, "<p class=\"font-semibold text-slate-800 text-sm\">");
    try out.appendSlice(allocator, "Order #");
    try appendValue(out, allocator, o.OrderID);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<span class=\"text-xs font-medium px-2 py-0.5 rounded-full bg-emerald-600 text-white\">");
    try out.appendSlice(allocator, "Ready");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</header>");
    try out.appendSlice(allocator, "<div class=\"px-4 py-3 space-y-2 text-xs text-slate-600\">");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-800\">");
    try appendValue(out, allocator, o.DeliveryAddress.Line1);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-slate-500\">");
    try appendValue(out, allocator, o.DeliveryAddress.City);
    try out.appendSlice(allocator, ",");
    try appendValue(out, allocator, o.DeliveryAddress.State);
    try appendValue(out, allocator, o.DeliveryAddress.Pincode);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex items-center justify-between border-t border-slate-100 pt-2\">");
    try out.appendSlice(allocator, "<span>");
    try appendValue(out, allocator, o.Items.len);
    try out.appendSlice(allocator, "item(s)");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<span class=\"font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, o.Total);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"px-4 pb-4\">");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"@post('/orders/");
    try appendValue(out, allocator, o.OrderKey);
    try out.appendSlice(allocator, "/status', {contentType: 'json', payload: {from: 'Ready', to: 'OutForDelivery'}})\" class=\"w-full py-2 rounded-md bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium transition\">");
    try out.appendSlice(allocator, "Pick up");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</article>");
    }
    }
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</section>");
    try out.appendSlice(allocator, "<section>");
    try out.appendSlice(allocator, "<div class=\"flex items-center justify-between mb-2 px-1\">");
    try out.appendSlice(allocator, "<h2 class=\"text-xs font-semibold text-slate-500 uppercase tracking-wider\">");
    try out.appendSlice(allocator, "Out for delivery");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<span class=\"text-xs text-slate-400\">");
    try out.appendSlice(allocator, "on the way");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"space-y-3\">");
    for (self.orders) |o| {
    if (o.isStatusCurrent("OutForDelivery")) {
    try out.appendSlice(allocator, "<article class=\"bg-white rounded-xl border border-blue-200 shadow-sm overflow-hidden\">");
    try out.appendSlice(allocator, "<header class=\"px-4 py-3 bg-blue-50 border-b border-blue-100 flex items-center justify-between\">");
    try out.appendSlice(allocator, "<p class=\"font-semibold text-slate-800 text-sm\">");
    try out.appendSlice(allocator, "Order #");
    try appendValue(out, allocator, o.OrderID);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<span class=\"text-xs font-medium px-2 py-0.5 rounded-full bg-blue-600 text-white\">");
    try out.appendSlice(allocator, "In transit");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</header>");
    try out.appendSlice(allocator, "<div class=\"px-4 py-3 space-y-2 text-xs text-slate-600\">");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-800\">");
    try appendValue(out, allocator, o.DeliveryAddress.Line1);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-slate-500\">");
    try appendValue(out, allocator, o.DeliveryAddress.City);
    try out.appendSlice(allocator, ",");
    try appendValue(out, allocator, o.DeliveryAddress.State);
    try appendValue(out, allocator, o.DeliveryAddress.Pincode);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"px-4 pb-4\">");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"@post('/orders/");
    try appendValue(out, allocator, o.OrderKey);
    try out.appendSlice(allocator, "/status', {contentType: 'json', payload: {from: 'OutForDelivery', to: 'Delivered'}})\" class=\"w-full py-2 rounded-md bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium transition\">");
    try out.appendSlice(allocator, "Mark delivered");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</article>");
    }
    }
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</section>");
    try out.appendSlice(allocator, "</div>");
    }
    try out.appendSlice(allocator, "</div>");

// #line 104 "src/features/delivery/zsx//delivery_dashboard.zsx"

    }
};

