// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/products/zsx//panel_home.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}


pub const PanelHome = struct {
    pub fn render(_: PanelHome, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 6 "src/features/products/zsx//panel_home.zsx"
        try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<div class=\"relative rounded-2xl overflow-hidden mb-8 bg-gradient-to-r from-blue-600 to-blue-800 text-white p-8 lg:p-12\">");
    try out.appendSlice(allocator, "<div class=\"relative z-10\">");
    try out.appendSlice(allocator, "<h1 class=\"text-3xl lg:text-4xl font-bold mb-2\">");
    try out.appendSlice(allocator, "Fresh from the Oven");
    try out.appendSlice(allocator, "</h1>");
    try out.appendSlice(allocator, "<p class=\"text-blue-100 text-lg mb-6\">");
    try out.appendSlice(allocator, "Hand-tossed pizzas, pastas, sides and more - delivered hot to your door");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<div class=\"flex gap-3\">");
    try out.appendSlice(allocator, "<button hx-get=\"/panel/catalogue\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-push-url=\"/catalogue\" class=\"bg-white text-blue-700 font-semibold px-6 py-2.5 rounded-xl hover:bg-blue-50 transition cursor-pointer\">");
    try out.appendSlice(allocator, "Order Now");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<button hx-get=\"/panel/catalogue?category=14\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-push-url=\"/?category=14\" class=\"border border-white/40 text-white font-medium px-6 py-2.5 rounded-xl hover:bg-white/10 transition cursor-pointer\">");
    try out.appendSlice(allocator, "View Combos");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"grid grid-cols-1 md:grid-cols-2 gap-4 mb-8\">");
    try out.appendSlice(allocator, "<div hx-get=\"/panel/catalogue?category=14\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-push-url=\"/?category=14\" class=\"bg-gradient-to-r from-emerald-500 to-teal-500 rounded-xl p-6 text-white cursor-pointer hover:shadow-lg transition\">");
    try out.appendSlice(allocator, "<p class=\"text-emerald-100 text-xs uppercase tracking-wider mb-1\">");
    try out.appendSlice(allocator, "Best Value");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<h3 class=\"text-xl font-bold mb-1\">");
    try out.appendSlice(allocator, "Family Feast for 4");
    try out.appendSlice(allocator, "</h3>");
    try out.appendSlice(allocator, "<p class=\"text-emerald-100 text-sm\">");
    try out.appendSlice(allocator, "2 Large Pizzas + Sides + Wings + Drinks - Save ₹350");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div hx-get=\"/panel/catalogue?category=2\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-push-url=\"/?category=2\" class=\"bg-gradient-to-r from-violet-500 to-purple-500 rounded-xl p-6 text-white cursor-pointer hover:shadow-lg transition\">");
    try out.appendSlice(allocator, "<p class=\"text-violet-100 text-xs uppercase tracking-wider mb-1\">");
    try out.appendSlice(allocator, "Premium Selection");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<h3 class=\"text-xl font-bold mb-1\">");
    try out.appendSlice(allocator, "Gourmet Pizzas");
    try out.appendSlice(allocator, "</h3>");
    try out.appendSlice(allocator, "<p class=\"text-violet-100 text-sm\">");
    try out.appendSlice(allocator, "Truffle, Lobster, Prosciutto and more artisan creations");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div hx-get=\"/panel/recent-orders\" hx-trigger=\"load\" hx-swap=\"innerHTML\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");

// #line 35 "src/features/products/zsx//panel_home.zsx"

    }
};

