// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/products/zsx//product_detail.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Product = @import("../models/product.zig").Product;

pub const ProductDetail = struct {
    product: Product,

    pub fn render(self: ProductDetail, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/features/products/zsx//product_detail.zsx"
        try out.appendSlice(allocator, "<div class=\"max-w-4xl mx-auto\">");
    try out.appendSlice(allocator, "<button class=\"text-sm text-blue-600 hover:text-blue-700 mb-4 flex items-center gap-1\" onclick=\"loadProducts()\">");
    try out.appendSlice(allocator, "<svg class=\"w-4 h-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">");
    try out.appendSlice(allocator, "<path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M15 19l-7-7 7-7\">");
    try out.appendSlice(allocator, "</path>");
    try out.appendSlice(allocator, "</svg>");
    try out.appendSlice(allocator, "Back to Products");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<div class=\"bg-white border border-slate-200 rounded-xl overflow-hidden\">");
    try out.appendSlice(allocator, "<div class=\"md:flex\">");
    try out.appendSlice(allocator, "<div class=\"md:w-1/2 h-72 md:h-auto bg-slate-100 relative overflow-hidden\">");
    if (self.product.ImageURL != null) {
    try out.appendSlice(allocator, "<img src=\"");
    try appendValue(out, allocator, self.product.ImageURL.?);
    try out.appendSlice(allocator, "\" alt=\"");
    try appendValue(out, allocator, self.product.Name);
    try out.appendSlice(allocator, "\" class=\"w-full h-full object-cover\" />");
    } else {
    try out.appendSlice(allocator, "<div class=\"w-full h-full flex items-center justify-center text-slate-300 min-h-[300px]\">");
    try out.appendSlice(allocator, "<svg class=\"w-20 h-20\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">");
    try out.appendSlice(allocator, "<path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z\">");
    try out.appendSlice(allocator, "</path>");
    try out.appendSlice(allocator, "</svg>");
    try out.appendSlice(allocator, "</div>");
    }
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"md:w-1/2 p-6 flex flex-col\">");
    try out.appendSlice(allocator, "<div class=\"mb-1\">");
    try out.appendSlice(allocator, "<span class=\"text-xs font-mono text-slate-400 bg-slate-100 px-2 py-0.5 rounded\">");
    try appendValue(out, allocator, self.product.SKU);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<h1 class=\"text-2xl font-bold text-slate-800 mb-2\">");
    try appendValue(out, allocator, self.product.Name);
    try out.appendSlice(allocator, "</h1>");
    if (self.product.Description != null) {
    try out.appendSlice(allocator, "<p class=\"text-slate-500 text-sm leading-relaxed mb-4\">");
    try appendValue(out, allocator, self.product.Description.?);
    try out.appendSlice(allocator, "</p>");
    }
    try out.appendSlice(allocator, "<div class=\"flex items-baseline gap-2 mb-6\">");
    try out.appendSlice(allocator, "<span class=\"text-3xl font-bold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, self.product.BasePrice);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<span class=\"text-sm text-slate-400\">");
    try out.appendSlice(allocator, "incl. taxes");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"grid grid-cols-2 gap-3 mb-6 text-sm\">");
    try out.appendSlice(allocator, "<div class=\"bg-slate-50 rounded-lg p-3\">");
    try out.appendSlice(allocator, "<span class=\"text-slate-400 text-xs\">");
    try out.appendSlice(allocator, "Category");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-700\">");
    try appendValue(out, allocator, self.product.CategoryID);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"bg-slate-50 rounded-lg p-3\">");
    try out.appendSlice(allocator, "<span class=\"text-slate-400 text-xs\">");
    try out.appendSlice(allocator, "Product ID");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-700\">");
    try appendValue(out, allocator, self.product.ProductID);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"mt-auto flex gap-3\">");
    try out.appendSlice(allocator, "<button class=\"flex-1 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-xl transition flex items-center justify-center gap-2\" onclick=\"addToCart(");
    try appendValue(out, allocator, self.product.ProductID);
    try out.appendSlice(allocator, ", '");
    try appendValue(out, allocator, self.product.Name);
    try out.appendSlice(allocator, "', ");
    try appendValue(out, allocator, self.product.BasePrice);
    try out.appendSlice(allocator, ")\">");
    try out.appendSlice(allocator, "<svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">");
    try out.appendSlice(allocator, "<path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 100 4 2 2 0 000-4z\">");
    try out.appendSlice(allocator, "</path>");
    try out.appendSlice(allocator, "</svg>");
    try out.appendSlice(allocator, "Add to Cart");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");

// #line 65 "src/features/products/zsx//product_detail.zsx"

    }
};

