// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/checkout/zsx//pay_page.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Order = @import("../../orders/models/order.zig").Order;

pub const PayPage = struct {
    order: Order,

    pub fn render(self: PayPage, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/features/checkout/zsx//pay_page.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"max-w-lg mx-auto p-4 lg:p-6\">");
    try out.appendSlice(allocator, "<div class=\"bg-white border border-slate-200 rounded-xl p-6\" data-init=\"mountStripePay('");
    try appendValue(out, allocator, self.order.OrderKey);
    try out.appendSlice(allocator, "')\">");
    try out.appendSlice(allocator, "<h1 class=\"text-lg font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "Pay for order #");
    try appendValue(out, allocator, self.order.OrderID);
    try out.appendSlice(allocator, "</h1>");
    try out.appendSlice(allocator, "<p class=\"text-sm text-slate-500 mt-1\">");
    try out.appendSlice(allocator, "Total ₹");
    try appendValue(out, allocator, self.order.Total);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<div id=\"payment-element\" class=\"mt-5\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<button type=\"button\" id=\"pay-btn\" onclick=\"confirmPayment('");
    try appendValue(out, allocator, self.order.OrderKey);
    try out.appendSlice(allocator, "')\" class=\"w-full py-2.5 mt-4 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium disabled:opacity-50\">");
    try out.appendSlice(allocator, "Pay ₹");
    try appendValue(out, allocator, self.order.Total);
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<p id=\"pay-error\" class=\"text-sm text-red-500 mt-2\">");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");

// #line 26 "src/features/checkout/zsx//pay_page.zsx"

    }
};

