// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/orders/zsx//order_detail.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Order = @import("../models/order.zig").Order;

pub const OrderDetail = struct {
    order: Order,
    sse_init: []const u8 = "",

    pub fn render(self: OrderDetail, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 10 "src/features/orders/zsx//order_detail.zsx"
        try out.appendSlice(allocator, "<div id=\"order-tracking-");
    try appendValue(out, allocator, self.order.OrderKey);
    try out.appendSlice(allocator, "\" class=\"max-w-xl mx-auto p-4 lg:p-6\" data-init=\"");
    try appendValue(out, allocator, self.sse_init);
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<a href=\"/orders\" data-on:click__prevent=\"@get('/orders')\" class=\"text-sm text-blue-600 hover:underline\">");
    try out.appendSlice(allocator, "&larr; Back to orders");
    try out.appendSlice(allocator, "</a>");
    try out.appendSlice(allocator, "<div class=\"bg-white rounded-2xl border border-slate-200 p-6 mt-3 mb-4 shadow-sm text-center\">");
    try out.appendSlice(allocator, "<div class=\"text-5xl mb-3\">");
    try appendValue(out, allocator, self.order.statusBadge());
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<h1 class=\"text-xl font-bold text-slate-800 mb-1\">");
    try out.appendSlice(allocator, "Tracking order #");
    try appendValue(out, allocator, self.order.OrderID);
    try out.appendSlice(allocator, "</h1>");
    try out.appendSlice(allocator, "<p class=\"text-slate-500 text-sm mb-3\">");
    try appendValue(out, allocator, self.order.statusMessage());
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400\">");
    try out.appendSlice(allocator, "Total:");
    try out.appendSlice(allocator, "<span class=\"font-semibold text-slate-600\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, self.order.Total);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    if (self.order.isCancelled()) {
    try out.appendSlice(allocator, "<div class=\"bg-red-50 border border-red-200 text-red-700 rounded-2xl p-5 text-center text-sm\">");
    try out.appendSlice(allocator, "This order was cancelled. The payment, if collected, will be refunded.");
    try out.appendSlice(allocator, "</div>");
    } else {
    try out.appendSlice(allocator, "<div class=\"bg-white rounded-2xl border border-slate-200 p-6 shadow-sm\">");
    try out.appendSlice(allocator, "<h2 class=\"text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4\">");
    try out.appendSlice(allocator, "Order progress");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<ol class=\"space-y-4\">");
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 ");
    try appendValue(out, allocator, self.order.stepTextClass("AwaitingPayment"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<div class=\"w-7 h-7 rounded-full border-2 ");
    try appendValue(out, allocator, self.order.stepRingClass("AwaitingPayment", "Paid"));
    try out.appendSlice(allocator, " flex items-center justify-center shrink-0\">");
    try out.appendSlice(allocator, "<div class=\"w-3 h-3 rounded-full ");
    try appendValue(out, allocator, self.order.stepDotClass("AwaitingPayment", "Paid"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex-1\">");
    try out.appendSlice(allocator, "<div class=\"text-sm font-medium\">");
    try out.appendSlice(allocator, "Order placed");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-xs\">");
    try out.appendSlice(allocator, "Waiting for payment");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 ");
    try appendValue(out, allocator, self.order.stepTextClass("Paid"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<div class=\"w-7 h-7 rounded-full border-2 ");
    try appendValue(out, allocator, self.order.stepRingClass("Paid", "Preparing"));
    try out.appendSlice(allocator, " flex items-center justify-center shrink-0\">");
    try out.appendSlice(allocator, "<div class=\"w-3 h-3 rounded-full ");
    try appendValue(out, allocator, self.order.stepDotClass("Paid", "Preparing"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex-1\">");
    try out.appendSlice(allocator, "<div class=\"text-sm font-medium\">");
    try out.appendSlice(allocator, "Payment received");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-xs\">");
    try out.appendSlice(allocator, "Sent to kitchen");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 ");
    try appendValue(out, allocator, self.order.stepTextClass("Preparing"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<div class=\"w-7 h-7 rounded-full border-2 ");
    try appendValue(out, allocator, self.order.stepRingClass("Preparing", "Ready"));
    try out.appendSlice(allocator, " flex items-center justify-center shrink-0\">");
    try out.appendSlice(allocator, "<div class=\"w-3 h-3 rounded-full ");
    try appendValue(out, allocator, self.order.stepDotClass("Preparing", "Ready"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex-1\">");
    try out.appendSlice(allocator, "<div class=\"text-sm font-medium\">");
    try out.appendSlice(allocator, "Preparing your order");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-xs\">");
    try out.appendSlice(allocator, "In the kitchen");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 ");
    try appendValue(out, allocator, self.order.stepTextClass("Ready"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<div class=\"w-7 h-7 rounded-full border-2 ");
    try appendValue(out, allocator, self.order.stepRingClass("Ready", "OutForDelivery"));
    try out.appendSlice(allocator, " flex items-center justify-center shrink-0\">");
    try out.appendSlice(allocator, "<div class=\"w-3 h-3 rounded-full ");
    try appendValue(out, allocator, self.order.stepDotClass("Ready", "OutForDelivery"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex-1\">");
    try out.appendSlice(allocator, "<div class=\"text-sm font-medium\">");
    try out.appendSlice(allocator, "Ready for pickup");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-xs\">");
    try out.appendSlice(allocator, "Waiting for delivery");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 ");
    try appendValue(out, allocator, self.order.stepTextClass("OutForDelivery"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<div class=\"w-7 h-7 rounded-full border-2 ");
    try appendValue(out, allocator, self.order.stepRingClass("OutForDelivery", "Delivered"));
    try out.appendSlice(allocator, " flex items-center justify-center shrink-0\">");
    try out.appendSlice(allocator, "<div class=\"w-3 h-3 rounded-full ");
    try appendValue(out, allocator, self.order.stepDotClass("OutForDelivery", "Delivered"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex-1\">");
    try out.appendSlice(allocator, "<div class=\"text-sm font-medium\">");
    try out.appendSlice(allocator, "Out for delivery");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-xs\">");
    try out.appendSlice(allocator, "On the way to you");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 ");
    try appendValue(out, allocator, self.order.stepTextClass("Delivered"));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "<div class=\"w-7 h-7 rounded-full border-2 ");
    try appendValue(out, allocator, self.order.stepRingClass("Delivered", ""));
    try out.appendSlice(allocator, " flex items-center justify-center shrink-0\">");
    try out.appendSlice(allocator, "<div class=\"w-3 h-3 rounded-full ");
    try appendValue(out, allocator, self.order.stepDotClass("Delivered", ""));
    try out.appendSlice(allocator, "\">");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex-1\">");
    try out.appendSlice(allocator, "<div class=\"text-sm font-medium\">");
    try out.appendSlice(allocator, "Delivered");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-xs\">");
    try out.appendSlice(allocator, "Enjoy your meal!");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    try out.appendSlice(allocator, "</ol>");
    try out.appendSlice(allocator, "<div class=\"mt-6 pt-4 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400\">");
    try out.appendSlice(allocator, "<span class=\"flex items-center gap-1.5\">");
    try out.appendSlice(allocator, "<span class=\"w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse\">");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "Live updates");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<a href=\"/\" data-on:click__prevent=\"@get('/')\" class=\"text-blue-600 hover:underline font-medium\">");
    try out.appendSlice(allocator, "Order again &rarr;");
    try out.appendSlice(allocator, "</a>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    }
    try out.appendSlice(allocator, "</div>");

// #line 98 "src/features/orders/zsx//order_detail.zsx"

    }
};



