// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/orders/zsx//order_list.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Order = @import("../models/order.zig").Order;

pub const OrderList = struct {
    orders: []Order,

    pub fn render(self: OrderList, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/features/orders/zsx//order_list.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"max-w-3xl mx-auto p-4 lg:p-6\">");
    try out.appendSlice(allocator, "<h1 class=\"text-xl font-semibold text-slate-800 mb-4\">");
    try out.appendSlice(allocator, "Your orders");
    try out.appendSlice(allocator, "</h1>");
    if (self.orders.len == 0) {
    try out.appendSlice(allocator, "<div class=\"bg-white border border-slate-200 rounded-xl p-10 text-center text-slate-400\">");
    try out.appendSlice(allocator, "<p class=\"text-sm\">");
    try out.appendSlice(allocator, "You haven't placed any orders yet.");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    } else {
    try out.appendSlice(allocator, "<ul class=\"space-y-3\">");
    for (self.orders) |o| {
    try out.appendSlice(allocator, "<li class=\"bg-white border border-slate-200 rounded-xl p-4 flex items-center justify-between hover:shadow-sm transition\">");
    try out.appendSlice(allocator, "<div class=\"min-w-0\">");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-800 text-sm\">");
    try out.appendSlice(allocator, "Order #");
    try appendValue(out, allocator, o.OrderID);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mt-0.5\">");
    try appendValue(out, allocator, o.CreatedAt);
    try out.appendSlice(allocator, "&middot;");
    try appendValue(out, allocator, o.Status);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-right shrink-0 ml-3\">");
    try out.appendSlice(allocator, "<p class=\"text-sm font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, o.Total);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<a href=\"/orders/");
    try appendValue(out, allocator, o.OrderKey);
    try out.appendSlice(allocator, "/tracking\" class=\"text-xs text-blue-600 hover:underline\">");
    try out.appendSlice(allocator, "Track");
    try out.appendSlice(allocator, "</a>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    }
    try out.appendSlice(allocator, "</ul>");
    }
    try out.appendSlice(allocator, "</div>");

// #line 32 "src/features/orders/zsx//order_list.zsx"

    }
};

