// AUTO-GENERATED by planctl v2, do not edit
// Source: src/zsx//admin_users_page.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const User = @import("../models/user.zig").User;

pub const AdminUsersPage = struct {
    users: []User,

    pub fn render(self: AdminUsersPage, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/zsx//admin_users_page.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"max-w-5xl mx-auto p-4 lg:p-6 grid grid-cols-1 md:grid-cols-3 gap-6\">");
    try out.appendSlice(allocator, "<section class=\"md:col-span-2 bg-white border border-slate-200 rounded-xl overflow-hidden\">");
    try out.appendSlice(allocator, "<header class=\"px-5 py-4 border-b border-slate-200\">");
    try out.appendSlice(allocator, "<h2 class=\"text-lg font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "Users");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mt-0.5\">");
    try out.appendSlice(allocator, "Promote staff to kitchen or delivery roles. The first signed-in user is auto-admin.");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</header>");
    if (self.users.len == 0) {
    try out.appendSlice(allocator, "<div class=\"px-5 py-10 text-center text-sm text-slate-400\">");
    try out.appendSlice(allocator, "No users yet. Sign in or create one →");
    try out.appendSlice(allocator, "</div>");
    } else {
    try out.appendSlice(allocator, "<ul class=\"divide-y divide-slate-100\">");
    for (self.users) |u| {
    try out.appendSlice(allocator, "<li class=\"px-5 py-3 flex items-center justify-between gap-3\">");
    try out.appendSlice(allocator, "<div class=\"min-w-0\">");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-800 text-sm\">");
    try appendValue(out, allocator, u.Name);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mt-0.5\">");
    try appendValue(out, allocator, u.Email);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"flex items-center gap-2 shrink-0\">");
    try out.appendSlice(allocator, "<span class=\"text-xs font-medium px-2 py-0.5 rounded-full bg-slate-100 text-slate-600\">");
    try appendValue(out, allocator, u.Role);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"@put('/admin/users/");
    try appendValue(out, allocator, u.UserID);
    try out.appendSlice(allocator, "/role', {contentType: 'json', payload: {role: 'admin'}})\" class=\"text-xs px-2 py-1 rounded-md bg-purple-50 text-purple-700 hover:bg-purple-100\">");
    try out.appendSlice(allocator, "Admin");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"@put('/admin/users/");
    try appendValue(out, allocator, u.UserID);
    try out.appendSlice(allocator, "/role', {contentType: 'json', payload: {role: 'kitchen'}})\" class=\"text-xs px-2 py-1 rounded-md bg-orange-50 text-orange-700 hover:bg-orange-100\">");
    try out.appendSlice(allocator, "Kitchen");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"@put('/admin/users/");
    try appendValue(out, allocator, u.UserID);
    try out.appendSlice(allocator, "/role', {contentType: 'json', payload: {role: 'delivery'}})\" class=\"text-xs px-2 py-1 rounded-md bg-green-50 text-green-700 hover:bg-green-100\">");
    try out.appendSlice(allocator, "Delivery");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"@put('/admin/users/");
    try appendValue(out, allocator, u.UserID);
    try out.appendSlice(allocator, "/role', {contentType: 'json', payload: {role: 'customer'}})\" class=\"text-xs px-2 py-1 rounded-md bg-slate-50 text-slate-600 hover:bg-slate-100\">");
    try out.appendSlice(allocator, "Customer");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    }
    try out.appendSlice(allocator, "</ul>");
    }
    try out.appendSlice(allocator, "</section>");
    try out.appendSlice(allocator, "<section class=\"bg-white border border-slate-200 rounded-xl p-5\">");
    try out.appendSlice(allocator, "<h2 class=\"text-lg font-semibold text-slate-800 mb-3\">");
    try out.appendSlice(allocator, "Add staff");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mb-4\">");
    try out.appendSlice(allocator, "Create a staff row in advance. They'll sign in via the OAuth flow; the row keyed on their email gets promoted to the role you set here.");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<form id=\"create-user-form\" class=\"space-y-3 text-sm\" data-on:submit__prevent=\"@post('/admin/users', {contentType: 'form'})\">");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Email");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"email\" type=\"email\" required class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Name");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"name\" class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Phone");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"phone\" class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Role");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<select name=\"role\" class=\"w-full px-3 py-2 border border-slate-200 rounded-md\">");
    try out.appendSlice(allocator, "<option value=\"kitchen\">");
    try out.appendSlice(allocator, "Kitchen");
    try out.appendSlice(allocator, "</option>");
    try out.appendSlice(allocator, "<option value=\"delivery\">");
    try out.appendSlice(allocator, "Delivery");
    try out.appendSlice(allocator, "</option>");
    try out.appendSlice(allocator, "<option value=\"admin\">");
    try out.appendSlice(allocator, "Admin");
    try out.appendSlice(allocator, "</option>");
    try out.appendSlice(allocator, "<option value=\"customer\">");
    try out.appendSlice(allocator, "Customer");
    try out.appendSlice(allocator, "</option>");
    try out.appendSlice(allocator, "</select>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<button type=\"submit\" class=\"w-full py-2.5 mt-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium\">");
    try out.appendSlice(allocator, "Add user");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</form>");
    try out.appendSlice(allocator, "</section>");
    try out.appendSlice(allocator, "</div>");

// #line 82 "src/zsx//admin_users_page.zsx"

    }
};

