// AUTO-GENERATED by planctl v2, do not edit
// Source: src/checkout/zsx//checkout_page.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Cart = @import("../../cart/models/cart.zig").Cart;

pub const CheckoutPage = struct {
    cart: Cart,

    pub fn render(self: CheckoutPage, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/checkout/zsx//checkout_page.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"max-w-4xl mx-auto p-4 lg:p-6 grid grid-cols-1 md:grid-cols-2 gap-6\">");
    try out.appendSlice(allocator, "<section class=\"bg-white border border-slate-200 rounded-xl p-5\">");
    try out.appendSlice(allocator, "<h2 class=\"text-lg font-semibold text-slate-800 mb-3\">");
    try out.appendSlice(allocator, "Your order");
    try out.appendSlice(allocator, "</h2>");
    if (self.cart.Items.len == 0) {
    try out.appendSlice(allocator, "<p class=\"text-sm text-slate-400\">");
    try out.appendSlice(allocator, "Your cart is empty.");
    try out.appendSlice(allocator, "</p>");
    } else {
    try out.appendSlice(allocator, "<ul class=\"divide-y divide-slate-100\">");
    for (self.cart.Items) |it| {
    try out.appendSlice(allocator, "<li class=\"py-2 flex items-center justify-between text-sm\">");
    try out.appendSlice(allocator, "<div class=\"min-w-0\">");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-800\">");
    try appendValue(out, allocator, it.Name);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, it.UnitPrice);
    try out.appendSlice(allocator, "×");
    try appendValue(out, allocator, it.Qty);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<span class=\"font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, it.LineTotal);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</li>");
    }
    try out.appendSlice(allocator, "</ul>");
    try out.appendSlice(allocator, "<div class=\"mt-3 pt-3 border-t border-slate-100 text-sm flex justify-between\">");
    try out.appendSlice(allocator, "<span class=\"text-slate-500\">");
    try out.appendSlice(allocator, "Subtotal");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<span class=\"font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, self.cart.computeSubtotal());
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mt-1\">");
    try out.appendSlice(allocator, "Tax + delivery fee calculated at confirmation.");
    try out.appendSlice(allocator, "</p>");
    }
    try out.appendSlice(allocator, "</section>");
    try out.appendSlice(allocator, "<section class=\"bg-white border border-slate-200 rounded-xl p-5\">");
    try out.appendSlice(allocator, "<h2 class=\"text-lg font-semibold text-slate-800 mb-3\">");
    try out.appendSlice(allocator, "Delivery address");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<form id=\"checkout-form\" class=\"space-y-3 text-sm\" data-on:submit__prevent=\"@post('/checkout', {contentType: 'form'})\">");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Label");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"addressLabel\" placeholder=\"Home / Office\" class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Address line 1");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"line1\" required class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Address line 2");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"line2\" class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"grid grid-cols-2 gap-3\">");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "City");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"city\" required class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "State");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"state\" required class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div>");
    try out.appendSlice(allocator, "<label class=\"block text-xs text-slate-400 mb-1\">");
    try out.appendSlice(allocator, "Pincode");
    try out.appendSlice(allocator, "</label>");
    try out.appendSlice(allocator, "<input name=\"pincode\" required class=\"w-full px-3 py-2 border border-slate-200 rounded-md\" />");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<button type=\"submit\" class=\"w-full py-2.5 mt-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium\">");
    try out.appendSlice(allocator, "Continue to payment");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</form>");
    try out.appendSlice(allocator, "</section>");
    try out.appendSlice(allocator, "</div>");

// #line 71 "src/checkout/zsx//checkout_page.zsx"

    }
};

