// AUTO-GENERATED by planctl v2, do not edit
// Source: src/zsx//category_list.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Category = @import("../models/product.zig").Category;

pub const CategoryList = struct {
    categories: []const Category,

    pub fn render(self: CategoryList, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/zsx//category_list.zsx"
        try out.appendSlice(allocator, "<aside id=\"category-list\" class=\"w-56 min-w-[14rem] bg-white border-r border-slate-200 overflow-y-auto shrink-0 p-4\">");
    try out.appendSlice(allocator, "<h2 class=\"text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3\">");
    try out.appendSlice(allocator, "Categories");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<button class=\"w-full text-left px-3 py-2 rounded-lg text-sm font-medium transition hover:bg-blue-50 hover:text-blue-700 category-btn\" data-category=\"all\">");
    try out.appendSlice(allocator, "All Items");
    try out.appendSlice(allocator, "</button>");
    for (self.categories) |cat| {
    try out.appendSlice(allocator, "<button class=\"w-full text-left px-3 py-2 rounded-lg text-sm transition hover:bg-blue-50 hover:text-blue-700 category-btn\" data-category=\"");
    try appendValue(out, allocator, cat.CategoryID);
    try out.appendSlice(allocator, "\" data-on:click=\"@get('/products?category=");
    try appendValue(out, allocator, cat.CategoryID);
    try out.appendSlice(allocator, "')\">");
    try appendValue(out, allocator, cat.Name);
    try out.appendSlice(allocator, "</button>");
    }
    try out.appendSlice(allocator, "</aside>");

// #line 23 "src/zsx//category_list.zsx"

    }
};

