// AUTO-GENERATED by planctl v2, do not edit
// Source: src/zsx//product_list.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Product = @import("../models/product.zig").Product;

pub const ProductList = struct {
    products: []const Product,

    pub fn render(self: ProductList, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/zsx//product_list.zsx"
        try out.appendSlice(allocator, "<div id=\"content\" class=\"p-4 lg:p-6\">");
    if (self.products.len == 0) {
    try out.appendSlice(allocator, "<div class=\"flex flex-col items-center justify-center py-20 text-slate-400\">");
    try out.appendSlice(allocator, "<svg class=\"w-16 h-16 mb-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">");
    try out.appendSlice(allocator, "<path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4\">");
    try out.appendSlice(allocator, "</path>");
    try out.appendSlice(allocator, "</svg>");
    try out.appendSlice(allocator, "<p class=\"text-lg font-medium\">");
    try out.appendSlice(allocator, "No products found");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-sm mt-1\">");
    try out.appendSlice(allocator, "Try selecting a different category");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    } else {
    try out.appendSlice(allocator, "<div class=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4\">");
    for (self.products) |product| {
    try out.appendSlice(allocator, "<div class=\"bg-white border border-slate-200 rounded-xl overflow-hidden hover:shadow-lg transition-shadow duration-200 flex flex-col\">");
    try out.appendSlice(allocator, "<div class=\"relative h-48 bg-slate-100 overflow-hidden\">");
    if (product.ImageURL != null) {
    try out.appendSlice(allocator, "<img src=\"");
    try appendValue(out, allocator, product.ImageURL.?);
    try out.appendSlice(allocator, "\" alt=\"");
    try appendValue(out, allocator, product.Name);
    try out.appendSlice(allocator, "\" class=\"w-full h-full object-cover\" loading=\"lazy\" />");
    } else {
    try out.appendSlice(allocator, "<div class=\"w-full h-full flex items-center justify-center text-slate-300\">");
    try out.appendSlice(allocator, "<svg class=\"w-12 h-12\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">");
    try out.appendSlice(allocator, "<path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z\">");
    try out.appendSlice(allocator, "</path>");
    try out.appendSlice(allocator, "</svg>");
    try out.appendSlice(allocator, "</div>");
    }
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"p-4 flex-1 flex flex-col\">");
    try out.appendSlice(allocator, "<h3 class=\"font-semibold text-slate-800 text-sm leading-tight mb-1 line-clamp-2\">");
    try appendValue(out, allocator, product.Name);
    try out.appendSlice(allocator, "</h3>");
    if (product.Description != null) {
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mb-3 line-clamp-2\">");
    try appendValue(out, allocator, product.Description.?);
    try out.appendSlice(allocator, "</p>");
    }
    try out.appendSlice(allocator, "<div class=\"mt-auto flex items-center justify-between pt-2 border-t border-slate-100\">");
    try out.appendSlice(allocator, "<span class=\"text-lg font-bold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, product.BasePrice);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<div class=\"flex items-center gap-2\">");
    try out.appendSlice(allocator, "<button class=\"p-2 rounded-lg text-white bg-blue-600 hover:bg-blue-700 transition\" data-product-id=\"");
    try appendValue(out, allocator, product.ProductID);
    try out.appendSlice(allocator, "\" data-on:click=\"@post('/items', {contentType: 'json', payload: { productId: ");
    try appendValue(out, allocator, product.ProductID);
    try out.appendSlice(allocator, ", name: '");
    try appendValue(out, allocator, product.Name);
    try out.appendSlice(allocator, "', unitPrice: ");
    try appendValue(out, allocator, product.BasePrice);
    try out.appendSlice(allocator, ", qty: 1}})\" title=\"Add to cart\">");
    try out.appendSlice(allocator, "<svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">");
    try out.appendSlice(allocator, "<path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 4v16m8-8H4\">");
    try out.appendSlice(allocator, "</path>");
    try out.appendSlice(allocator, "</svg>");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    }
    try out.appendSlice(allocator, "</div>");
    }
    try out.appendSlice(allocator, "</div>");

// #line 51 "src/zsx//product_list.zsx"

    }
};

