// AUTO-GENERATED by planctl v2, do not edit
// Source: src/cart/zsx//cart_drawer.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Cart = @import("../models/cart.zig").Cart;

pub const CartDrawer = struct {
    cart: Cart,

    pub fn render(self: CartDrawer, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 9 "src/cart/zsx//cart_drawer.zsx"
        try out.appendSlice(allocator, "<div id=\"cart-drawer\" class=\"h-full flex flex-col absolute right-0 top-0 bottom-0 w-full max-w-md bg-white shadow-2xl\">");
    try out.appendSlice(allocator, "<header class=\"flex items-center justify-between px-5 py-4 border-b border-slate-200\">");
    try out.appendSlice(allocator, "<h2 class=\"text-lg font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "Your cart");
    try out.appendSlice(allocator, "</h2>");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"$cartOpen = false\" class=\"cursor-pointer text-slate-400 hover:text-slate-600 text-2xl leading-none\">");
    try out.appendSlice(allocator, "&times;");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</header>");
    if (self.cart.Items.len == 0) {
    try out.appendSlice(allocator, "<div class=\"flex-1 flex flex-col items-center justify-center text-slate-400 px-6 text-center\">");
    try out.appendSlice(allocator, "<span class=\"text-5xl mb-3\">");
    try out.appendSlice(allocator, "🛒");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<p class=\"text-sm\">");
    try out.appendSlice(allocator, "Your cart is empty");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs mt-1\">");
    try out.appendSlice(allocator, "Add some pizza to get started");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "</div>");
    } else {
    try out.appendSlice(allocator, "<ul class=\"flex-1 overflow-y-auto divide-y divide-slate-100\">");
    for (self.cart.Items) |it| {
    try out.appendSlice(allocator, "<li class=\"flex items-start gap-3 p-4\">");
    try out.appendSlice(allocator, "<div class=\"flex-1 min-w-0\">");
    try out.appendSlice(allocator, "<p class=\"font-medium text-slate-800 line-clamp-2 text-sm\">");
    try appendValue(out, allocator, it.Name);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<p class=\"text-xs text-slate-400 mt-0.5\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, it.UnitPrice);
    try out.appendSlice(allocator, "each");
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<div class=\"mt-2 inline-flex items-center gap-2\">");
    try out.appendSlice(allocator, "<button class=\"w-7 h-7 rounded-md bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold leading-none\" data-on:click=\"@put('/items', {contentType: 'json', payload: {productId: ");
    try appendValue(out, allocator, it.ProductID);
    try out.appendSlice(allocator, ", qty: ");
    try appendValue(out, allocator, it.Qty - 1);
    try out.appendSlice(allocator, "}})\" title=\"Decrease\">");
    try out.appendSlice(allocator, "−");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "<span class=\"text-sm font-medium w-6 text-center\">");
    try appendValue(out, allocator, it.Qty);
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<button class=\"w-7 h-7 rounded-md bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold leading-none\" data-on:click=\"@put('/items', {contentType: 'json', payload: {productId: ");
    try appendValue(out, allocator, it.ProductID);
    try out.appendSlice(allocator, ", qty: ");
    try appendValue(out, allocator, it.Qty + 1);
    try out.appendSlice(allocator, "}})\" title=\"Increase\">");
    try out.appendSlice(allocator, "+");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<div class=\"text-right shrink-0\">");
    try out.appendSlice(allocator, "<p class=\"text-sm font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, it.LineTotal);
    try out.appendSlice(allocator, "</p>");
    try out.appendSlice(allocator, "<button class=\"mt-1 text-xs text-red-500 hover:underline\" data-on:click=\"@delete('/items?productId=");
    try appendValue(out, allocator, it.ProductID);
    try out.appendSlice(allocator, "')\" title=\"Remove\">");
    try out.appendSlice(allocator, "Remove");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "</li>");
    }
    try out.appendSlice(allocator, "</ul>");
    try out.appendSlice(allocator, "<footer class=\"border-t border-slate-200 px-5 py-4\">");
    try out.appendSlice(allocator, "<div class=\"flex items-center justify-between text-sm mb-3\">");
    try out.appendSlice(allocator, "<span class=\"text-slate-500\">");
    try out.appendSlice(allocator, "Subtotal");
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "<span class=\"font-semibold text-slate-800\">");
    try out.appendSlice(allocator, "₹");
    try appendValue(out, allocator, self.cart.computeSubtotal());
    try out.appendSlice(allocator, "</span>");
    try out.appendSlice(allocator, "</div>");
    try out.appendSlice(allocator, "<button type=\"button\" data-on:click=\"$cartOpen = false; @get('/checkout')\" class=\"w-full py-2.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-medium\">");
    try out.appendSlice(allocator, "Proceed to checkout");
    try out.appendSlice(allocator, "</button>");
    try out.appendSlice(allocator, "</footer>");
    }
    try out.appendSlice(allocator, "</div>");

// #line 61 "src/cart/zsx//cart_drawer.zsx"

    }
};

