// AUTO-GENERATED by planctl v2, do not edit
// Source: src/cart/zsx//cart_badge.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}


pub const CartBadge = struct {
    total: u32,

    pub fn render(self: CartBadge, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 8 "src/cart/zsx//cart_badge.zsx"
        try out.appendSlice(allocator, "<span id=\"cart-badge\" class=\"absolute -top-1 -right-1 min-w-[18px] h-[18px] px-1 rounded-full bg-blue-600 text-white text-xs flex items-center justify-center\">");
    try appendValue(out, allocator, self.total);
    try out.appendSlice(allocator, "</span>");

// #line 12 "src/cart/zsx//cart_badge.zsx"

    }
};

