// AUTO-GENERATED by planctl v2, do not edit
// Source: src/features/cart/zsx//item_list.zsx
const std = @import("std");
const web = @import("web");

fn appendValue(out: *std.ArrayList(u8), allocator: std.mem.Allocator, value: anytype) !void {
    const T = @TypeOf(value);
    const info = @typeInfo(T);
    if (T == []const u8 or T == []u8) {
        try web.appendEscaped(out, allocator, value);
    } else if (info == .optional) {
        if (value) |v| try appendValue(out, allocator, v);
    } else if (info == .int or info == .comptime_int) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .float or info == .comptime_float) {
        try out.print(allocator, "{d}", .{value});
    } else if (info == .bool) {
        try out.appendSlice(allocator, if (value) "true" else "false");
    } else {
        try out.appendSlice(allocator, "[unsupported]");
    }
}

const Item = @import("../models/item.zig").Item;

 // Render component - writes HTML directly to the writer.
pub const ItemList = struct {
    items: []const Item,

    pub fn render(self: ItemList, out: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
        // #line 10 "src/features/cart/zsx//item_list.zsx"
        try out.appendSlice(allocator, "<div class=\"page\">");
    try out.appendSlice(allocator, "<h1>");
    try out.appendSlice(allocator, "Items");
    try out.appendSlice(allocator, "</h1>");
    try out.appendSlice(allocator, "<table class=\"striped\">");
    try out.appendSlice(allocator, "<thead>");
    try out.appendSlice(allocator, "<tr>");
    try out.appendSlice(allocator, "<th>");
    try out.appendSlice(allocator, "ID");
    try out.appendSlice(allocator, "</th>");
    try out.appendSlice(allocator, "<th>");
    try out.appendSlice(allocator, "Name");
    try out.appendSlice(allocator, "</th>");
    try out.appendSlice(allocator, "<th>");
    try out.appendSlice(allocator, "Price");
    try out.appendSlice(allocator, "</th>");
    try out.appendSlice(allocator, "</tr>");
    try out.appendSlice(allocator, "</thead>");
    try out.appendSlice(allocator, "<tbody>");
    for (self.items) |item| {
    try out.appendSlice(allocator, "<tr>");
    try out.appendSlice(allocator, "<td>");
    try appendValue(out, allocator, item.id);
    try out.appendSlice(allocator, "</td>");
    try out.appendSlice(allocator, "<td>");
    try appendValue(out, allocator, item.name);
    try out.appendSlice(allocator, "</td>");
    try out.appendSlice(allocator, "<td>");
    try appendValue(out, allocator, item.price);
    try out.appendSlice(allocator, "</td>");
    try out.appendSlice(allocator, "</tr>");
    }
    try out.appendSlice(allocator, "</tbody>");
    try out.appendSlice(allocator, "</table>");
    try out.appendSlice(allocator, "</div>");

// #line 31 "src/features/cart/zsx//item_list.zsx"

    }
};

